### ISSUE TITLE
Vue JS support

### ISSUE THREAD

**Issue by rkg0612** [pion/ion-sdk-js#10]
Does this have a VueJS support? Because I can't seem to make it work. If so, do you have any documentations I can follow? Thanks!

**Comment by tarrencev** [comment]
It should work with VueJS. What issue are you seeing? It is not coupled to any view library

**Comment by rkg0612** [comment]
> It should work with VueJS. What issue are you seeing? It is not coupled to any view library

I already made it work. Thought it won't work because it failed to connect the first few times to my websocket. Thanks though. A documentation would be a big help. Hehe.

**Comment by tarrencev** [comment]
Feel free to add some!
