### ISSUE TITLE
Firefox: Using five or more STUN/TURN servers causes problems

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sdk-js#123]
Got these errors when using firefox:

WebRTC: Using more than two STUN/TURN servers slows down discovery 2 ion-sdk.min.js line 1 > eval:13
WebRTC: Using five or more STUN/TURN servers causes problems ion-sdk.min.js line 1 > eval:13

![image](https://user-images.githubusercontent.com/12995347/100530454-4e175080-322d-11eb-9383-c86528824b70.png)

**Comment by tarrencev** [comment]
interesting. we can reduce to just two

**Comment by adwpc** [comment]
now is two.
