### ISSUE TITLE
Join with RoomId and UserId

### ISSUE THREAD

**Issue by edwinsyarief** [pion/ion-sdk-js#141]
Hi,

I'm trying to use the latest ion-sdk-js. How to join into roomId with userId, because, I only see that join function is only one parameter.

![image](https://user-images.githubusercontent.com/13018338/104686312-87e5dd00-572f-11eb-8685-86d3427781af.png)

Thank you.

Best Regards,
Edwin

**Comment by anhhd2703** [comment]
with the latest version, you need to create a userId when connect WebSocket. You must push userId as a param.
ws://127.0.0.1:8443/ws?uid=f25982ca-347e-4307-8ae5-e6c465dffb7a

**Comment by edwinsyarief** [comment]
@anhhd2703, I see. And how to get the param from ion-sdk-js ?

Thank you

**Comment by anhhd2703** [comment]
> @anhhd2703, I see. And how to get the param from ion-sdk-js for other participant for example client.ontrack?
> 
> Thank you

![image](https://user-images.githubusercontent.com/54494592/105146401-8a32a780-5b32-11eb-9696-3c664262a5cb.png)
You need a change a little bit in ion-sdk-js
![image](https://user-images.githubusercontent.com/54494592/105146652-cebe4300-5b32-11eb-922b-4cc6949bccbd.png)
In your case, i think you need to add only userId to param

**Comment by anhhd2703** [comment]
if you can fix you can contact me via sky : live:hoangducanh_t59

**Comment by adwpc** [comment]
@edwinsyarief @anhhd2703 
What do you use uid for？

**Comment by edwinsyarief** [comment]
@adwpc , I was thinking how to pass additional information in json format or query string param. if possible. But, you've answered it.

Thanks & Regards,
Edwin

**Comment by edwinsyarief** [comment]
Hi @adwpc ,

How to know the stream id is owned by which user id? at client.ontrack ?

Thank you
