### ISSUE TITLE
How to create recvonly  client?

### ISSUE THREAD

**Issue by mango009** [pion/ion-sdk-js#142]
Hi,

Is there anyway to create the client with recvonly option? I simply just want to receive remote stream without publishing.

Thanks.

**Comment by tarrencev** [comment]
Hi @mango009,

The simplest way is to implement your own signaling module that does not negotiate the sub peer connection. The other option is to modify the sfu to not offer the sub pc, but that is a bit more involved

**Comment by adwpc** [comment]
Yep. you don't need publish localstream
