### ISSUE TITLE
Switch camera to desktop capture

### ISSUE THREAD

**Issue by edwinsyarief** [pion/ion-sdk-js#147]
Hi Anyone,

Can someone give some example how to switch camera to desktop capture? or maybe camera to desktop capture + camera.

Thank you.

Best Regards,
Edwin

**Comment by adwpc** [comment]
https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by edwinsyarief** [comment]
Hi @adwpc ,

Thanks for response. But I'm not asking about the switch hardware, I'm was asking about how to switch camera into share screen in realtime. Is it possible in this sdk?

Thanks & Regards,
Edwin

**Comment by aixinaxc** [comment]
adopt LocalStream.getDisplayMedia Can share desktop video stream
```
const dispaly = await LocalStream.getDisplayMedia({
                    audio: true,
                    video: true,
                    simulcast: true, // enable simulcast
                })
                
                await this.CLIENT.publish(dispaly);
```

**Comment by edwinsyarief** [comment]
Sorry, but what I meant that are we able to share screen like this:
![image](https://user-images.githubusercontent.com/13018338/108154491-8719df80-710f-11eb-8adc-9b2a1ef50bf1.png)
using this sdk?
Because I need to be able to share screen.

And also, when we switch between camera and screen sharing, is it possible doing like this?

```
        LocalStream.getUserMedia({
          audio: false,
          video: {
            mandatory: {
              chromeMediaSource: "screen",
              maxWidth: 1280,
              maxHeight: 720,
            },
            optional: [],
          },
        }).then(async (stream) => {
          console.log(stream);
          thiz.currentStream.removeTrack(thiz.currentVideoTrack);
          thiz.currentVideoTrack.stop();
          let newVideoTrack = stream.getVideoTracks()[0];
          thiz.currentStream.addTrack(newVideoTrack);
          thiz.currentVideoTrack = newVideoTrack;
          let video = document.getElementById("vrStreamVideo");
          if (video !== null && video !== undefined) {
            video.srcObject = thiz.currentStream;
          }
        });
```
Because the code above is not working. Please help.
Thanks in advance

**Comment by edwinsyarief** [comment]
Sorry, @aixinaxc it works. Thanks

**Comment by edwinsyarief** [comment]
@aixinaxc , how to replace track previous stream video track with new share screen track? Because I don't want the stream id changed

**Comment by aixinaxc** [comment]
adopt this.CLIENT.publish (dispaly) push the shared stream, and you can see it from the far end

```
async OpenDisplayMedia(){
                const dispaly = await LocalStream.getDisplayMedia({
                    audio: true,
                    video: true,
                    simulcast: true, // enable simulcast
                })
                this.$refs.mainVideo.srcObject = dispaly //Load stream to video
                await this.CLIENT.publish(dispaly);  // Push the stream to the far end
            }
```

**Comment by edwinsyarief** [comment]
When I've tried this, changes still not showing, still showing the old video, and after a couple seconds, the sfu is down:
![image](https://user-images.githubusercontent.com/13018338/108164801-16c98900-7124-11eb-9901-5752facc3285.png)

**Comment by aixinaxc** [comment]
Is your ion SFU the latest version

**Comment by edwinsyarief** [comment]
Yes, the ion sfu is the latest from git. And the ion sdk js version 1.6.0

**Comment by aixinaxc** [comment]
> 
> 
> Yes, the ion sfu is the latest from git. And the ion sdk js version 1.6.0.
> 
> I have also tried sfu 1.9.0 with sdk js 1.6.0, still not update the screen share on the participants, the participants still see the host's face

You can pull my project for testing. My project is based on Vue and webpack. He's available for sharing screens
[https://github.com/aixinaxc/starlight](https://github.com/aixinaxc/starlight)

**Comment by edwinsyarief** [comment]
@aixinaxc ,

thank you, but in my case, when the host changing between camera to share screen, the stream id must be the same.
So, I was doing:

```
currentStream.removeTrack(currentStream.getVideoTracks()[0]);
currentStream.addTrack(newStream.getVideoTracks()[0]);
```

Am I doing it wrong?

Thank you

**Comment by edwinsyarief** [comment]
It is working now. There is no issue anymore about switching camera to screen share
