### ISSUE TITLE
sreen shareing 

### ISSUE THREAD

**Issue by aliaaaaaaaaa** [pion/ion-sdk-js#195]
how we can sreeen share to other peer

**Comment by adwpc** [comment]
https://github.com/pion/ion-app-web/blob/a2e26d13bf4e7696b8cd23ff3887cd53b3599862/src/Conference.jsx#L126

**Comment by aliaaaaaaaaa** [comment]
> https://github.com/pion/ion-app-web/blob/a2e26d13bf4e7696b8cd23ff3887cd53b3599862/src/Conference.jsx#L126

 const localVideo = document.getElementById("local-video");
    

        const serverUrl = "wss://dara.darademo.ir/sfu-ws";


  
        const signalLocal = new IonSFUJSONRPCSignal(serverUrl)

        this.clientLocal = new Client(signalLocal);
        let clientLocal = this.clientLocal
        signalLocal.onopen = () => {
          clientLocal.join("test 1")
          console.log("test")
        };
        const streams = {};
   
       

        let constraints;
        LocalStream.getDisplayMedia(constraints = {
          codec: 'vp8',
          resolution: 'hd',
          audio: true,
          video: true,
          simulcast: false,
        })
       
            .then((media) => {
              this.stream = media;
              localVideo.srcObject = media;
              localVideo.autoplay = true;
              localVideo.controls = true;
              localVideo.muted = true;
              clientLocal.publish(media);
            })
            .catch(console.error);
this is code i use for screen sharing but it not working can you tell me why?

**Comment by jason-shen** [comment]
LocalStream.getDisplayMedia({
      codec: 'vp8',
      resolution: 'hd',
      audio: true,
      video: true,
      simulcast: false,
    })

**Comment by jason-shen** [comment]
try that you don't need that constraints =
