### ISSUE TITLE
NextJS ReferenceError: MediaStream is not defined

### ISSUE THREAD

**Issue by mattjslaton** [pion/ion-sdk-js#229]
Library installs fine, but when I go to import anything from 'ion-sdk-js' I get the message, "ReferenceError: MediaStream is not defined" is this a normal bug when using this library with NextJS? Any workarounds? I would love to get it working with my NextJS project. Thanks

**Comment by lakshmanpasala** [comment]
Are you importing this sdk in SSR component? I would suggest you use dynamic import to load this only on the client side.

**Comment by jason-shen** [comment]
here is a little tip for you for nextjs, try to wrap the component that has the ion-sdk-js in a second level rather than call it straight, as nextjs is a server side thing it doesn't not have the browser stuff until its fully loaded
