### ISSUE TITLE
safari does not support extending native classes

### ISSUE THREAD

**Issue by kasparsj** [pion/ion-sdk-js#26]
### Your environment.
  - Version: latest
  - Browser: Safari 13.1.1
  - Other Information - stream.publish(this.rid) is undefined

### What did you do?
Tried ion on Safari

### What did you expect?
To work

### What happened?
Didn't work

The problem is with `LocalStream` and `RemoteStream` classes, because they extend `Stream` which extends native `MediaStream`. A workaround that would be to add `Object.setPrototypeOf(this, RemoteStream.prototype);` in both constructors, as per this post: https://stackoverflow.com/questions/58471434/problem-extending-native-es6-classes-in-safari

**Comment by tarrencev** [comment]
@kasparsj thanks for reporting with the work around. Would you mind opening a PR with the change?

**Comment by kasparsj** [comment]
okay, will do

**Comment by kasparsj** [comment]
was about to do it, but it's done already. @greko6 thanks!

**Comment by greko6** [comment]
@kasparsj : yw! Thanks for the pointer! However, in my app, I still cannot receive the video. Could you test it on your side, please? I wonder if that's my logic in the app, or something else that is missing when it comes to RemoteStream?

**Comment by sibis** [comment]
I still cannot receive the video with latest update. Is this working for you guys?

**Comment by greko6** [comment]
@sibis : I did find the root cause, here is another issue https://github.com/pion/ion-sfu/issues/23 .
