### ISSUE TITLE
Implement grpc-web signaling module

### ISSUE THREAD

**Issue by tarrencev** [pion/ion-sdk-js#59]
Would be great to support a `IonSFUGRPCSignal` module using [`grpc-web`](https://github.com/grpc/grpc-web)

**Comment by cloudwebrtc** [comment]
I did some tests and grpc-web is also suitable for flutter web
https://github.com/grpc/grpc-dart

So it might be a good choice to switch to grpc.

**Comment by tarrencev** [comment]
cool. now it is possible to support many different signaling types. unfortunately it looks like `grpc-web` doesnt support bidirectional streaming right now. so that would be an issue for web

**Comment by cloudwebrtc** [comment]
`dart-grpc` for web supports server-side streaming, Can receive messages from the go server.
Not sure if the client-side stream is supported, but it should be possible to call a certain method repeatedly to send signaling.

**Comment by cloudwebrtc** [comment]
https://github.com/grpc/grpc-web/commit/83cb0406c1ea0d7404e36772011d9a2a4a2d2a05

**Comment by cloudwebrtc** [comment]
@tarrencev https://github.com/improbable-eng/grpc-web Here is a ts version that can do two-way streaming through WebSocket. I tested its example and it works.

**Comment by tarrencev** [comment]
awesome. we should give it a shot!

**Comment by adwpc** [comment]
would be awsome to support ion signal
