### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by adwpc** [pion/ion-sdk-js#6]
## Firefox Support
This is the Browser Market Share Worldwide:
https://gs.statcounter.com/browser-market-share#monthly-201903-202003-bar
Chrome has > 60% share worldwide

Ion support chrome well, but on firefox, we need to do many work（low priority）:
1. use _payloadModify(in Client.js) to modify the sdp when publish or subscribe

on chrome, we use 111 for opus, 96 for vp8 and 102 for h264 ,as a reference
we should do this for firefox

2. test audio and video between firefox to firefox  , firefox to chrome

3. other js bug on firefox

If anyone can help, that would be awsome!

**Comment by Leeaandrob** [comment]
there any news abotu this issue?

**Comment by OrlandoCo** [comment]
Why it's not possible to set the webrtc transceiver direction to "sendonly" in Pion? I tried to set it but it sends an error that only "recvonly" and "sendrecv" is supported. 

Change the client to "sendrecv" in the subscription makes that all borwsers doesn't display the video.

**Comment by tarrencev** [comment]
@OrlandoCo I'm not sure. pion/webrtc might be a better place to ask.

**Comment by tarrencev** [comment]
@Leeaandrob No updates yet. Feel free to contribute!

**Comment by tarrencev** [comment]
@jbrady42 should we close this?

**Comment by jbrady42** [comment]
This was implemented server side in the SFU.
