### ISSUE TITLE
How do I subscribe/unsubcribe to specific streams with v1.0.7 ?

### ISSUE THREAD

**Issue by mishig25** [pion/ion-sdk-js#84]
When I was using v0.4.1, I can subscribe to specific streams by `const remote = client.subscribe(mid);` (example use case is: there 50 peers in a room, and at any moment, I only need to subscribe to 5 of the peers who are talking and ignore the other 45).
How can I achieve the same functionality with v1.0.7 ? I see that  `subscribe, unsubscribe` methods are removed from `Client` class.
Thank you very much. Really appreciate what you all doing with ION!

**Comment by tomsun** [comment]
I had a similar reaction to that change. Here's another discussion
https://github.com/pion/ion-sfu/issues/62#issuecomment-667680054

And simulcast support seems to exist now:
https://github.com/pion/ion-sfu/pull/189
https://github.com/pion/ion-sdk-js/pull/47

**Comment by tarrencev** [comment]
yes, you can mute tracks now. we still need to add a config to unmute by default. in that case, you would receive 50 muted tracks and unmute 5 of them

**Comment by mishig25** [comment]
got it; thanks for the answer!
