### ISSUE TITLE
如何让流携带上用户ID

### ISSUE THREAD

**Issue by aixinaxc** [pion/ion-sdk-js#91]
在新的版本中，join方法中只有sid，offer。我该如何携带用户ID或者其他额外信息。

**Comment by adwpc** [comment]
目前不可以，不过改起来不难

**Comment by adwpc** [comment]
supported

**Comment by adwpc** [comment]
@aixinaxc 是否方便说一下，你使用uid的场景是什么？

**Comment by aixinaxc** [comment]
> 
> 
> @aixinaxc 是否方便说一下，你使用uid的场景是什么？

现在加入房间只有房间信息，流id是随机生成的。这样就不方便确定这个流是那个用户的。如果携带上用户信息就可以以用户id或者其他信息作为流的id。这样可以根据需要把流和用户绑定在一起
